# Cheetah's Homegrown Alacritty Config

# General configuration
live_config_reload = true

# Shell
[shell]
program = "/bin/zsh"
args = []

# Fonts
[font]
size = 10.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

# Colors (Everforest Dark)

# Default colors 
[colors.primary]
background = '#272e33'
foreground = '#d3c6aa'

# Normal colors 
[colors.normal]
black = '#475258'
red = '#e67e80'
green = '#a7c080'
yellow = '#dbbc7f'
blue = '#7fbbb3'
magenta = '#d699b6'
cyan = '#83c092'
white = '#d3c6aa'

# Bright colors 
[colors.bright]
black = '#475258'
red = '#e67e80'
green = '#a7c080'
yellow = '#dbbc7f'
blue = '#7fbbb3'
magenta = '#d699b6'
cyan = '#83c092'
white = '#d3c6aa'
